# Generated by Django 4.0.4 on 2022-06-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posted_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_assignee',
            field=models.CharField(max_length=250),
        ),
    ]
