# Generated by Django 4.0.4 on 2022-05-09 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posted_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_tasks', to='posted_app.taskgroup'),
        ),
    ]
