# Generated by Django 4.0.4 on 2022-05-30 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posted_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_users',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_team', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
