# Generated by Django 4.0.4 on 2022-05-09 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posted_app', '0002_alter_task_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
    ]
