# Generated by Django 4.0.4 on 2022-05-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posted_app', '0003_remove_team_team_users_team_team_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
